export { AcontextVsClaude, default } from './acontext-vs-claude'
export { SpiralCanvas } from './spiral-canvas'
export { SceneContent } from './scene-content'
export { ComparisonCard } from './comparison-card'
export { TypewriterCodeBlock } from './code-block'
export { scenes, colorSchemes } from './scene-data'
export type { Scene, CardData, CodeLine, ColorStop } from './scene-data'
